name: Check Internal 404 Errors

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run internal links checker
        id: check
        run: |
          echo "## Internal Links Check Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          # Run the checker and capture output
          if node scripts/check-internal-links.cjs > check-output.txt 2>&1; then
            echo "✅ All internal links are valid!" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            cat check-output.txt >> $GITHUB_STEP_SUMMARY
            exit 0
          else
            echo "❌ Found issues with internal links" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            cat check-output.txt >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY

            # Also output to console
            cat check-output.txt

            # Fail the build if there are errors
            if grep -q "🚨 ERRORS" check-output.txt; then
              echo "::error::Found critical 404 errors. Check the summary for details."
              exit 1
            fi
          fi

      - name: Comment on PR
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const output = fs.readFileSync('check-output.txt', 'utf8');

            const body = `## ❌ Internal Links Check Failed

Found issues with internal links. Please review and fix before merging.

<details>
<summary>View Details</summary>

\`\`\`
${output}
\`\`\`

</details>
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
